use mnm_webtintuc;
insert into tbl_categories(id, name_categories,status) values(1,"Tin mới",1);
insert into tbl_categories(id, name_categories,status) values(2,"Công nghệ",1);
insert into tbl_categories(id, name_categories,status) values(3,"Thế giới",1);
insert into tbl_categories(id, name_categories,status) values(4,"Xã hội",1);
insert into tbl_admin(id,address,descri,dob, email, fullname, pass, phone, position,stt) values(1,'Việt Nam','Admin quan lý','1999-10-06','vt.arrow.06@gmail.com','Nguyễn Việt Hưng','admin123','0975968806','Admin',0);
insert into tbl_user(id,email,pass, status,username) values (1,'vt.arrow.06@gmail.com','user123',0,'Nguyễn Việt Hưng');

insert into tbl_post(id, create_date, description,details, image, status, title,view, idCategory) values(null,'2020-12-27',
'Sự việc được quan tâm khi đoạn video ghi lại cảnh một phụ nữ mặc áo Grabbike ôm mặt khóc nức nở ngay giữa phố đông đúc, tại Hà Nội, vào ngày 27/12.',
'<p>Theo những nội dung mà nữ tài xế kể lại, cô chở một nam thanh niên đi từ Trần Nhật Duật đến chợ Nghĩa Tân (quận Cầu Giấy, Hà Nội).</p>
<p>Tuy nhiên, sau khi xuống xe, nam khách hàng đã ngỏ ý mượn điện thoại để vào trong chợ chụp mẫu hàng.</p><p>Do quá tin người nên nữ tài xế này đã không ngần ngại cho nam khách hàng mượn và đứng bên ngoài chợ Nghĩa Tân chờ.</p>
<p>Do quá tin người nên nữ tài xế này đã không ngần ngại cho nam khách hàng mượn và đứng bên ngoài chợ Nghĩa Tân chờ.</p>
<p>Tuy nhiên, sau khoảng 15 phút chờ đợi thì nữ tài xế không thấy nam khác hàng trở ra. Do quá sốt ruột, nữ tài xế này vào tận phía trong chợ Nghĩa Tân để tìm và đòi lại điện thoại nhưng không thấy bóng dáng nam khách hàng nữa.</p>

<p>Lúc này, nữ tài xế đi ra ngoài mượn điện thoại của một người khác gọi điện về cho người thân, rồi ôm mặt khóc nức nở vì lỡ tin lời khách mà để mất chiếc điện thoại.</p>
<p>Ngay sau khi biết mình bị lừa lấy điện thoại, nữ tài xế đã ôm mặt khóc nức nở giữa khu chợ Nghĩa Tân. Khoảnh khắc này đã được những người đi đường ghi lại và đăng tải lên mạng xã hội.</p>
<p>Sự việc đã thu hút sự quan tâm của dư luận. Không ít người đã dành sự thương cảm đến cô gái nhưng cũng không quên trách cô vì đã quá tin người.</p>
<p>Một tài khoản có tên H.K bình luận: "Chắc do chị mới đi làm nên mới dễ tin người. Khổ thân chị, Tết nhất đến nơi rồi".</p>
<p>Hiện tại, câu chuyện trên vẫn đang gây xôn xao trên khắp các diễn đàn mạng xã hội. Đã có không ít người bày tỏ muốn tặng nữ tài xế điện thoại mới để tiếp tục công việc những ngày cuối năm.</p>
','grab-16090633431041747324187-1609063377391896158098.png',1,'Nữ tài xế Grab khóc nức nở giữa phố vì bị khách lừa lấy điện thoại',0,4);

insert into tbl_post(id, create_date, description,details, image, status, title,view, idCategory) values(null,'2020-12-27',
'Liên quan vụ bé trai 4 tuổi bị người nhà cầm kéo đâm xuyên mắt, cơ quan công an đã khởi tố vụ án cố ý gây thương tích, tạm giữ hình sự đối với Katơr Hasi Gô.',
'<p>Sáng 26/12, trao đổi trên báo VOV, anh Nguyễn Văn Thu – Chủ tịch xã Lâm Sơn, huyện Ninh Sơn, tỉnh Ninh Thuận - cho biết, Công an huyện Ninh Sơn đã khởi tố vụ án cố ý gây thương tích, tạm giữ hình sự đối với Katơr Hasi Gô (SN 1986, người dân tộc K’ho ở thôn Lập Lá).</p>
<p>Nạn nhân là cháu M.N.C.N.K, 4 tuổi (con chị vợ của Gô).</p>
<p>Chủ tịch xã Lâm Sơn cho biết, cháu K., được mẹ gửi nhờ nhà dì ruột trông hộ do bận việc đồng áng. Tại đây, người dượng (chồng của dì) sau khi nhậu về đã cầm kéo đâm xuyên mắt cháu. Người nhà rút kéo ra rồi đưa đi cấp cứu tại Bệnh viện tỉnh Ninh Thuận trong tình trạng chảy máu, hôn mê. Sau đó bệnh nhi đã được chuyển đến Bệnh viện Nhi đồng 2 (TP.HCM). Tại đây, bé Khải đã được phẫu thuật cấp cứu.</p>
<p>Trao đổi trên báo Đất Việt, chị M.N.K. (mẹ bé K.) cho biết, bé K. rất ngoan, đôi khi có nghịch ngợm một chút nhưng đó là do tính hiếu động của trẻ con.</p>
<p>"Giờ em chỉ biết mong bác sĩ cứu lấy con trai em, nó đáng thương, có tội tình gì đâu. Cha nó mới mất hồi tháng 8, giờ mà nó có bị làm sao chắc em không sống nổi", mẹ bé K. chia sẻ thêm.</p>
<p>Trong diễn biến có liên quan, ngày 25/12, trao đổi trên Tri thức trực tuyến, bác sĩ Nguyễn Văn Lộc, Trưởng khoa Hồi sức tích cực - Chống độc, Bệnh viện Nhi đồng 2 - cho biết hậu phẫu, bệnh nhi tạm ổn định sinh hiệu, không ghi nhận hiện tượng xuất huyết. Tuy nhiên, tình trạng của bé được tiên lượng còn rất nặng, điểm thần kinh chỉ đạt 5 trong thang điểm 15. Ngoài ra, bé cần được theo dõi sát để dự phòng các diễn biến xấu với tổn thương này.</p>
<p>"Đây là tổn thương vĩnh viễn không thể hồi phục. Các bác sĩ đang được theo dõi diễn biến để có kế hoạch điều trị tiếp theo cho bé. Ngoài ra, chúng tôi vẫn theo dõi sát tổn thương mắt của bé, dự phòng nhiễm nhiễm trùng. Đây là vấn đề quan trọng nhất quyết định khả năng hồi phục của bé trong giai đoạn này", bác sĩ Lộc nói.</p>
<p>Theo bác sĩ Đặng Ngọc Dũng, Trưởng bộ phận trực cấp cứu ngoại thần kinh của Bệnh viện Nhi Đồng 2 cho biết, khi bị hung khí đâm vào một bộ phận nào đó trên cơ thể, người nhà không nên tự ý rút hung khí ra mà nên chuyển bệnh nhân đến ngay các cơ sở cấp cứu.</p>
<p><em>Nguồn: doisongphapluat .com/tin-tuc/tin-trong-nuoc/vu-be-trai-4-tuoi-bi-nguoi-nha-cam-keo-dam-xuyen-mat-dam-nuoc-mat-loi-nguoi-me-a350753.html</em></p>',
'1609065144-26de0f0b15d42437a961e8afa3a27991.jpg',1,'Vụ bé trai 4 tuổi bị người nhà cầm kéo đâm xuyên mắt: Đẫm nước mắt lời người mẹ',0,4);

insert into tbl_post(id, create_date, description,details, image, status, title,view, idCategory) values(null,'2020-12-11',
'Tổng thống tân cử Joe Biden vẫn chưa được tiếp cận điện mừng của nhiều nước gửi, do chính quyền của Tổng thống Trump cấm ông tiếp cận tại Bộ Ngoại giao.',
'<div>Đài CNN ngày 12.11 dẫn nguồn từ các quan chức Bộ Ngoại giao Mỹ cho hay cơ quan này đang giữ một số lượng lớn những bức điện do lãnh đạo các nước gửi cho <a href="https://thanhnien.vn/the-gioi/cuoc-dua-trump-biden-chua-ket-thuc-quy-trinh-chuyen-giao-quyen-luc-da-san-sang-1300906.html" target="_blank" rel="">Tổng thống tân cử Mỹ Joe Biden</a>, trong khi chính quyền của Tổng thống Donald Trump <a href="https://thanhnien.vn/the-gioi/ong-biden-xuc-tien-nhan-chuyen-giao-quyen-luc-1302670.html" target="_blank" rel="">cản trở</a> ông Biden tiếp cận. </div>
<div>Trước nay, Bộ Ngoại giao ủng hộ mọi liên lạc với tổng thống tân cử nên nhiều nước gửi điện đến bộ. Tuy nhiên, nhiều bức điện vẫn chưa đến tay ông Biden vì tổng thống tân cử này hiện bị chính quyền đương nhiệm cấm tiếp cận nguồn lực của Bộ Ngoại giao, lý do là vì Tổng thống Trump chưa công nhận chiến thắng của đảng Dân chủ.</div>
<div><a href="http://thanhnien.vn/the-gioi/bau-cu-my-tong-thong-trump-khong-chia-se-thong-tin-tinh-bao-mat-cho-ong-biden-1303760.html" style="color:#d00 !important;font-weight:bold;text-decoration:none;" rel="">&gt;&gt; Bầu cử Mỹ: Tổng thống Trump không chia sẻ thông tin tình báo mật cho ông Biden </a></div>
<div>Sau khi ông Biden giành đa số phiếu cử tri, nhóm thực hiện chiến dịch của ông đã liên<a href="https://thanhnien.vn/the-gioi/ong-biden-noi-gi-trong-lan-dau-dien-dam-voi-lanh-dao-3-nuoc-domg-minh-1303861.html" target="_blank" rel=""> lạc với nhiều chính phủ nước ngoài</a> mà không có sự liên quan của Bộ Ngoại giao. Bên cạnh đó, ông cũng điện đàm với nhiều lãnh đạo như Thủ tướng Đức Angela Merkel và <a href="https://thanhnien.vn/thu-tuong-canada/" rel="">Thủ tướng Canada</a> Justin Trudeau. </div>
<div>Tuy nhiên, các cuộc điện đàm không được Bộ Ngoại giao hỗ trợ về hậu cần và phiên dịch. </div>
<div>Một nguồn tin cho biết nhóm của ông Biden muốn sử dụng nguồn lực của Bộ Ngoại giao vì họ đã gặp phải nhiều khó khăn không lường trước khi thực hiện các cuộc điện đàm. </div>
<div>Ông Biden không chỉ bị chặn tiếp cận tại Bộ Ngoại giao mà còn bị Ngoại trưởng Mike Pompeo từ chối công nhận chiến thắng khi cho hay “sẽ có sự <a href="https://thanhnien.vn/video/the-gioi/ngoai-truong-my-se-co-chuyen-giao-quyen-luc-cho-nhiem-ky-2-cua-tong-thong-trump-155591.html" target="_blank" rel="">chuyển giao êm thấm</a> cho chính quyền thứ 2 của ông Trump”.</div>
<div>Hiện Tổng thống tân cử còn bị ngăn không được tiếp cận các báo cáo tình báo hằng ngày. Các lãnh đạo nước ngoài bắt đầu nhận thấy Bộ Ngoại giao Mỹ không giúp họ tiếp cận với Tổng thống tân cử Biden và đội ngũ của ông. Do đó, có bên nhờ các cựu nhân viên ngoại giao dưới thời Tổng thống Barack Obama giúp đỡ về cách thức gửi điện chúc mừng ông Biden, theo các nguồn tin.</div>',
'063_1284987599_rjdo.jpg',1,'Vì sao điện mừng từ các nước chưa đến tay ông Biden?',0,3);

insert into tbl_post(id, create_date, description,details, image, status, title,view, idCategory) values(null,'2020-12-25',
'Trump thảo luận hơn một tiếng với Pence ngay sau khi ông kêu gọi "phó tướng" không công nhận kết quả bỏ phiếu của đại cử tri đoàn.',
'<p class="Normal">Các nguồn thạo tin cho biết cuộc gặp giữa Tổng thống Mỹ Donald Trump và Phó tổng thống Mike Pence diễn ra tại Phòng Bầu dục hôm 23/12, sau khi Trump nhiều lần phàn nàn "phó tướng" của ông chưa nỗ lực hết mình để lật ngược kết quả bầu cử.</p>
<p class="Normal">Vài giờ trước khi gặp Pence, Trump đã chia sẻ lại dòng tweet kêu gọi Phó tổng thống "hành động" và không phê chuẩn kết quả bỏ phiếu của đại cử tri đoàn trong phiên họp lưỡng viện quốc hội hôm 6/1.</p>
<p class="Normal">Một người thạo tin cho biết cuộc thảo luận hôm 23/12 "không liên quan" đến dòng tweet, song không nói rõ liệu chủ đề về cuộc họp phê chuẩn kết quả ngày 6/1 của quốc hội có được hai người nêu ra hay không.</p>
<p class="Normal">Các nguồn tin cho hay Trump những ngày gần đây đã bày tỏ thắc mắc về việc tại sao Pence, với tư cách Chủ tịch Thượng viện chủ trì cuộc họp quốc hội ngày 6/1, không thể tự đảo ngược kết quả phiếu đại cử tri và trao chiến thắng cho ông.</p>
<p class="Normal">Pence và nhiều trợ lý Nhà Trắng đã nỗ lực giải thích với Trump rằng vai trò Chủ tịch Thượng viện của Phó Tổng thống chủ yếu mang tính hình thức và ông không thể nào đơn phương bác bỏ kết quả bỏ phiếu của các đại cử tri.</p>
<p class="Normal">Sau khi kết thúc cuộc thảo luận với Pence, Tổng thống Mỹ cùng Đệ nhất phu nhân&nbsp;tới Florida để đón Giáng sinh. Rudy Giuliani, luật sư riêng của Trump, cũng đi cùng Tổng thống tới dinh thự Mar-a-Lago và dự kiến tiếp tục cùng nhau thảo luận về nỗ lực "lật kèo" kết quả bầu cử ở quốc hội.</p>
<p class="Normal">Ngày 6/1, quốc hội Mỹ sẽ họp toàn thể dưới sự chủ trì của Phó tổng thống Mỹ và cũng là Chủ tịch Thượng viện Mike Pence, nhằm xác nhận phiếu bầu của đại cử tri đoàn các bang. Đại cử tri đoàn hôm 14/12 đã hoàn tất quá trình bỏ phiếu, với 306 phiếu cho Joe Biden và 232 phiếu cho Tổng thống Trump.</p>
<p class="Normal">Trước ngày 6/1, thay vì nhận thua, Trump cùng các đồng minh vẫn thực hiện nhiều kế hoạch nhằm đảo ngược kết quả bầu cử. Tổng thống Mỹ còn cảnh báo sẽ xảy ra cuộc&nbsp;biểu tình&nbsp;"rầm rộ" tại thủ đô Washington vào ngày xác nhận kết quả bầu cử.</p>',
'556318717130a-Trump-6527-16082-5072-4285-1608860379.jpg',1,'Trump gặp Pence sau khi kêu gọi "lật kèo" bầu cử',0,3);

insert into tbl_post(id, create_date, description,details, image, status, title,view, idCategory) values(null,'2020-12-24',
'Một trận giao hữu nội bộ, có sự chênh lệch về trình độ thì sự xuất hiện của nhiều bàn thắng chẳng có gì đáng nói, nhất là với đội “đàn em” U22 Việt Nam. Nhưng có những lúc trên khán đài HLV Park Hang-seo không thể cười.',
'<p class="Normal">Trong khoảng 13 tình huống nguy hiểm được tạo ra trước khung thành hai đội, có đến chín lần, cơ hội được tạo ra do các hậu vệ đứng sai vị trí, không kèm người hoặc bị đánh vỗ mặt không chủ động phản ứng. Bốn trong tổng số năm bàn trận này thực ra cũng là hậu quả của lỗi phòng ngự. Ví dụ, bàn gỡ 1-1 của Văn Quyết phút 26 chỉ là pha đệm bóng không người kèm dễ dàng, từ một pha tiếp bóng lỗi của Hà Đức Chinh khiến cú sút biến thành một đường chuyền ngang thuận lợi. Nhưng trước đó, phải kể đến cú cản phá hụt của hậu vệ U22 Việt Nam, bóng mới đến với Đức Chinh. Hoặc như bàn nâng tỷ số lên 2-1 của U22 Việt Nam có công lớn của hậu vệ Văn Việt bên phía đội tuyển quốc gia, khi anh xô ngã tiền đạo đối phương một cách thô thiển dù bóng đã ở phía rìa vùng cấm.</p>
<p class="Normal">Sai sót là một phần không thể thiếu ở một trận giao hữu, khi các cầu thủ khó mà đạt được trạng thái tập trung cao nhất, nhưng những cái sai đó có thể thông cảm nếu nó thuộc về yếu tố mới lạ chiến thuật, chưa quen với cách vận hành sơ đồ thi đấu. Vấn đề ở đây là có nhiều sai sót mang yếu tố cá nhân, lại diễn ra trong một trận đấu mà HLV Park Hang-seo cố tình bỏ qua khâu chiến thuật, ngồi lên khán đài để tập trung vào các màn trình diễn của từng cầu thủ.</p>
<p class="Normal"><strong>Mục đích này được thể hiện rõ qua cách thầy Park xếp đội hình ra sân đá trận đầu tiên trong hai trận giao hữu nội bộ cách nhau bốn ngày</strong>. 11 cầu thủ đầu tiên, bao gồm cả Đức Chinh mới bước qua độ tuổi U22, đều được xem là cầu thủ mới. Với những cầu thủ này, chỉ hơn tuần lễ tập trung, về nguyên tắc thì không thể nào chơi nhuần nhuyễn về mặt chiến thuật. Nghĩa là, dù đội tuyển chơi không tốt, nhận kết quả tệ, chiến thuật không rõ ràng thì cũng không vấn đề gì. Nhưng chừng đó thời gian vẫn đủ để họ nắm bắt được cái khái niệm hay yêu cầu về vị trí từ HLV Park. Nói cách khác, họ cần đá tròn vai, thể hiện đúng phẩm chất tốt nhất cho vị trí mà nhờ đó họ được triệu tập. Tiền đạo không được phép bỏ lỡ cơ hội mười mươi, thủ môn không được phép mắc sai lầm, hậu vệ cần hạn chế mắc lỗi cá nhân hay bị đối phương qua người... Đây là các yếu tố cá nhân, phản ánh năng lực hay tư duy chơi bóng tốt hay kém.</p>
<div class="fig-picture"><img class="lazy lazied" style="display: block; margin-left: auto; margin-right: auto;" src="https://i1-thethao.vnecdn.net/2020/12/24/ff0b301dfaa80bf652b9-160879624-2189-7667-1608796291.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=PSE8yyaXLlBkkgrGcM_tkg" alt="Chưa thể nói lên nhiều điều từ trận giao hữu này, nhưng những điều HLV Park thu lượm được có thể chưa đủ để ông hài lòng. Ảnh: Giang Huy." data-src="https://i1-thethao.vnecdn.net/2020/12/24/ff0b301dfaa80bf652b9-160879624-2189-7667-1608796291.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=PSE8yyaXLlBkkgrGcM_tkg" data-ll-status="loaded"></div>
<p class="Image" style="text-align: center;">Chưa thể nói lên nhiều điều từ trận giao hữu này, nhưng những điều HLV Park thu lượm được có thể chưa đủ để ông hài lòng. Ảnh:&nbsp;<em>Giang Huy.</em></p>
<p class="Normal">Nếu căn cứ trên mục đích ấy, có lẽ chỉ hai cầu thủ đá hàng công là Văn Quyết và Đức Chinh làm tốt phần nhiệm vụ với hai bàn thắng. Nhưng từ phía sau lưng họ trở xuống thì không ổn. HLV Park thừa nhận đội tuyển bị gãy ở tuyến giữa, không có tiền vệ đánh chặn lẫn thu hồi bóng, hàng thủ vì vậy bị các "đàn em" đánh vỗ mặt, tiêu biểu như bàn mở tỷ số khi ba cái bóng áo trắng đá một chạm với ba đường chuyền bằng chân trái đã đưa bóng gọn gàng vào lưới thủ môn Tấn Trường mà hầu như không để cho các trung vệ đội tuyển kịp can thiệp.</p>
<p class="Normal">Tại V-League 2020, ba đội dẫn đầu là Viettel, Hà Nội, Sài Gòn FC đều để thủng lưới chưa đến 20 bàn, tức là trung bình chưa đến một bàn mỗi trận. Đây là con số tốt nhất tính trong 10 mùa gần nhất, khi đa số các nhà vô địch trước đó đều thủng lưới trung bình 1,2 bàn mỗi trận. Sự cạnh tranh khốc liệt của V-League mùa vừa qua đã khiến cho các hệ thống phòng ngự được nâng cấp, dù chất lượng của các hàng tấn công vẫn mạnh như trước. Về lý thuyết, điều này sẽ giúp cho bóng đá Việt Nam có thêm các trung vệ hay tiền vệ đánh chặn chất lượng trong bối cảnh mà những Đình Trọng, Duy Mạnh, Văn Hậu... đang gặp chấn thương liên tục, còn ở vị trí trung tâm thì Đỗ Hùng Dũng đã cày ải quá nhiều. Tiếc là, ngay bài kiểm tra đầu tiên của năm 2020, HLV Park lại có thêm mối lo khi hệ thống phòng thủ của ông chưa tìm được các nhân vật có chất lượng. Nhà cầm quân Hàn Quốc vốn dĩ đã than thở không tìm ra tiền đạo mới, giờ đây ngay chính ở khu vực vốn được xem là điểm mạnh nhất, là bệ phóng chiến thuật quen thuộc của ông, lại không thể có sự yên tâm với lực lượng dự bị.</p>
<p class="Normal">Mối lo ấy càng dễ thấy hơn khi trong hiệp hai, các cầu thủ vào thay người ở hàng sau như Xuân Trường, Xuân Mạnh, Trọng Hoàng hay Hoàng Đức đều có thiên hướng tấn công. Đó là lúc mà HLV Park phải chấp nhận lấy công, bù thủ khi con người trong tay đã không còn ai để thử nghiệm. Nỗi lo của ông có... đáng lo không, thì cần đến trận kế tiếp, khi nhiều khả năng là đội hình mạnh nhất sẽ ra sân.</p>
','930060fc2249d3178a58-160879610-5063-7365-1608796291.jpg',1,'Mối lo của thầy Park',0,1);

insert into tbl_post(id, create_date, description,details, image, status, title,view, idCategory) values(null,'2020-12-28',
'Hệ thống thu phí không dừng ePass có khả năng xử lý mỗi giao dịch trong 0,2 giây, dự kiến sẽ triển khai ở 35 trạm thu phí trên cả nước trong năm nay.',
'<p class="Normal">Thách thức được Bộ Giao thông Vận tải đặt ra cho hệ thống thu phí không dừng tại Việt Nam là cần đọc được dữ liệu của xe đang di chuyển với tốc độ 40 km/h, đồng thời xử lý giao dịch trong thời gian dưới 200 mili giây. Yêu cầu này có nghĩa là khi xe đi đến gần barrier của trạm thu phí, giao dịch đã hoàn thành và barrier mở lên để xe đi qua.</p>
<p class="Normal">VDTC - công ty thành viên của Viettel và là đơn vị trực tiếp phát triển ePass - đã giải được bài toán này. Đại diện công ty cho biết, thời gian chung để barrier tại trạm thu phí nâng lên là khoảng 0,6 giây, còn thời gian hệ thống ePass xử lý giao dịch thu phí là 0,2 giây, nên mỗi xe qua trạm sẽ chỉ mất tổng cộng chưa đến một giây cho việc thu phí.</p>
<p class="Normal">Theo tính toán của VDTC, các xe sẽ không phải dừng khi đi qua trạm thu phí, do đó, tiết kiệm thời gian hơn 60 lần so với sử dụng cách soát vé thủ công. Tuy nhiên, các xe cần đảm bảo một số điều kiện, như tài khoản còn đủ tiền, thẻ dán trên xe không bị hỏng, tốc độ qua trạm dưới 40 km/h...</p>
<p class="Normal">Cơ chế chung việc thu phí tự động là người dùng sẽ tạo một tài khoản trên hệ thống, có thông tin về xe, chủ xe, sau đó nạp sẵn tiền hoặc liên kết với ngân hàng. Mỗi tài khoản sẽ được cấp một tấm thẻ dán kính lái phía trước xe. Khi đi đến gần trạm thu phí có hỗ trợ công nghệ này, hệ thống sẽ đọc thông tin từ tấm thẻ hoặc biển số, thu phí đường bộ từ tài khoản của người dùng. Nếu giao dịch thành công, barrier sẽ tự động mở. Người dùng không cần dừng xe, trả tiền mặt, mua vé... như cách truyền thống.</p>
<p class="Normal">Theo VDTC, đây là một hệ thống phức tạp, kết hợp nhiều công nghệ từ vô tuyến, truyền dẫn, cơ điện, cho đến hệ thống tính cước, quản lý khách hàng, hậu kiểm. Đơn vị này phải ứng dụng nhiều công nghệ có sẵn trong hệ sinh thái của Viettel, như OCR để đọc thông tin từ giấy tờ, giúp người dùng đăng ký tài khoản qua mạng; hệ thống tính cước thời gian thức OCS; giải pháp thanh toán qua ví điện tử, ngân hàng...</p>
<p class="Normal">Người đi xe có thể đăng ký sử dụng dịch vụ qua ứng dụng hoặc website ePass, thanh toán phí đường bộ bằng Viettel Pay, Momo, thẻ Visa hoặc tài khoản 40 ngân hàng trong nước.</p>
<p class="Normal">ePass dự kiến triển khai vào ngày 29/12 tới, song song với giải pháp của một đơn vị khác là VETC. Viettel cho biết sẽ triển khai đồng loạt 35 trạm thu phí ở cả ba miền Bắc, Trung, Nam, trong đó, 25 trạm do đơn vị này thực hiện theo cam kết với Tổng cục Đường bộ, 10 trạm là liên kết với các nhà đầu tư BOT.</p>
<p class="Normal">Tuy nhiên, đại diện đơn vị phát triển cho rằng các hệ thống thu phí ở Việt Nam vẫn chỉ ở giai đoạn khởi đầu và đang phải đối mặt với nhiều thách thức, như tỷ lệ xe sử dụng còn thấp; dữ liệu của 2 nhà cung cấp (VETC và VDTC) chưa đồng bộ...</p>
<p class="Normal">Việt Nam hiện có khoảng 3,8 triệu ôtô đang lưu thông, nhưng theo đại diện VDTC, lượng xe dán thẻ thu phí không dừng mới đạt khoảng một triệu, trong đó, khoảng 30% ở trạng thái hoạt động. Hiện trạng là nhiều xe không đăng ký thu phí tự động đi nhầm làn, dẫn đến tắc nghẽn. Ngoài ra, nhiều chủ xe không tuân thủ tốc độ quy định 40 km/h dẫn đến nguy cơ đâm vào barrier.</p>
<p class="Normal">Trên thế giới hiện có 50 nước triển khai hệ thống thu phí không dừng, trong đó có 13 nước tại châu Á. Tuy nhiên, các nước trên thế giới sử dụng hệ thống thu phí Free Flow - trạm thu phí không cần barrier và xe có thể chạy suốt và việc tính phí được thực hiện sau.</p>
','thuphi-khongdung-viettel-vdtce-5410-8733-1609091982.jpg',1,'Công nghệ thu phí đường bộ trong 0,2 giây',0,2);
